### ISSUE TITLE
When Running Demo Snakemake Crashes

### ISSUE THREAD

**Issue by JooshK** [Arcadia-Science/ProteinCartography#88]
### Description of the bug

I created a conda environment and ran the demo using 4 cores, at step 13 the an error in rule asses_pdbs occurred as as a python AttributeError of the module arcadia pycolor, missing an atribute 'Gradients'. Thanks in advance for your help:

### Command used and terminal output

```console
$ snakemake --snakefile Snakefile --configfile demo/search-mode/config_actin.yml --use-conda --cores 4
...
Activating conda environment: .snakemake/conda/0edc9d41bbd7c35062b5ad31e774a114_
Traceback (most recent call last):
  File "/home/oconnorlab/joshuak/protein_cartography/ProteinCartography/ProteinCartography/assess_pdbs.py", line 10, in <module>
    from color_utils import RESIDUE_CONFIDENCE_COLORS
  File "/home/oconnorlab/joshuak/protein_cartography/ProteinCartography/ProteinCartography/color_utils.py", line 7, in <module>
    arcadia_viridis = apc.Gradients["arcadia:viridis"].grad_nested_list
AttributeError: module 'arcadia_pycolor' has no attribute 'Gradients'. Did you mean: 'gradients'?
```

### Relevant files

[2024-07-12T121623.218462.snakemake.log](https://github.com/user-attachments/files/16197897/2024-07-12T121623.218462.snakemake.log)

### System information

Desktop, Ubuntu Linux 22.04
Snakemake: 7.25.3
Version v0.5

**Comment by keithchev** [comment]
This should be fixed by #89. Please let us know if you encounter any other problems!
